Trezor integration PoC #964 (#1150)
* The starting point for working with Trezor
* Add WebUSB driver that is used/planning to be used by Trezor and Ledger
* Add TrezorClient implementation that allows to init a session and get PublicKey and UTXO address
* Add the 'test_trezor' test suit for the web example
* Update web-sys to 0.3.55

* Commit missing files

* The starting point for working with Ledger (doesn't work at all)

* Add a sketch of hid_driver to hw_common/transport

* Add 'libusb' to 'hw_common/transport'
* Add 'UsbTransport' for Trezor

* Prepare TrezorClient for integration into mm2
* Add CryptoCtx that consists of either KeyPair or HardwareWallet
* Add MmError::split and MmError::new_with_trace
* Replace KeyDerivationPath with bip32::DerivationPath
* Refactor TrezorResponse to avoid declaring 'Req' type and lifetime param

* Add a RPC task manager that will return a task status and handle user action

* Commit missing files

* * Add 'MmInitTask' that can wait for user actions like entering Trezor pin
* Add `MmInitError`, 'OrdermatchInitError', extend `P2PInitError`
* Move 'lp_protocol' into 'common::mm_rpc_protocol'
* Rename dispatcher_v2.rs to dispatcher.rs
* Add the 'mmrpc: 2.0h' protocol
* Refactor 'lp_init' to allow initializing `CryptoCtx` with either passphrase or Hardware Wallet device
* Refactor 'init_and_migrate_db' to avoid deadlocking

* Add 'TrezorClient::sign_tx'

* Sign first RICK, QTUM transactions using Trezor
* Add 'utxo_signer', move all functions related to signing UTXO transactions to this crate
* Add and implement 'TrezorSigner' that interacts with 'TrezorClient'
* Add PoC 'WithdrawTask', 'init_withdraw', 'withdraw_status'
* Remove 'mmrpc: 2.0h'

* Add missing files

* Refactor 'TrezorClient', 'CryptoCtx'
* Remove an instance of 'TrezorClient' from 'CryptoCtx'
* Replace direct using 'secp256k1_key_pair' with 'CryptoCtx::secp256k1_pubkey' in some places

* Finish implementing 'init_withdraw'
* Add the 'trezor_coin' field to coins config
* Move 'utxo_common::withdraw' to 'utxo_withdraw.rs', refactor it by converting the function to 'UtxoWithdraw'
* Remove 'WithdrawTaskError'
* Add the 'InitWithdrawCoin' trait, implement it for 'UtxoStandardCoin' and 'QtumCoin'

* Add the 'withdraw_user_action' RPC call

* Prepare UtxoCoinFields for HD wallets support
* Replace 'UtxoCoinFields::my_address' with 'UtxoCoinFields::address_mode'
* Replace 'UtxoCoinFields::key_pair' with 'UtxoCoinFields::priv_key_policy'
* Add 'init_utxo', 'init_utxo_status' RPC calls

* Make 'RpcTaskManager' generic
* Move 'common::rpc_task' into the 'rpc_task' crate
* Add 'CoinsActivationContext', 'MmInitContext'

* Push missing files

* Remove protoc-rust code generation from the 'trezor' crate
* Add 'trezor/src/proto/message*' fiels generated by 'protoc-rust'

* Fix Zcoin compile errors

* Minor changes
* Remove excess the 'hidapi' dependency
* Remove unused 'test_trezor' WASM static function

* Fix compilation error
* Comment out 'hid_driver' transport within 'hw_common' crate
* Remove 'test_trezor' from WASM test suit

* Bump wasm-bindgen-test-runner v0.2.78

* PR fixes - iteration#1
* Rename and refactor 'AddressMode' to 'DerivationMethod'
* Move 'DerivationMethod' and 'PrivKeyPolicy' to 'lp_coins', make them generic
* Add 'TxProviderError', return it instead of 'UtxoSignTxError' from 'TxProvider::get_rpc_transaction'

* Fix rustfmt warnings

* Replace 'protoc-rust' with 'prost-build'
* Display 'from' address of the 'init_withdraw' RPC call

* Change withdraw display message

* Add button acknowledging confirmation

* Unite 'in_progress', 'awaiting', 'finished' containers to 'tasks' by adding 'TaskStatusExt'

* Make `TrezorClient` thread-safe
* Add `TrezorSession` that is a wrapper over mutex guard
* Keep the connection to a Trezor device in `HwWalletContext` while it's alive

* Fix WASM compilation error

* Fix ZCoin compilation error

* Reinitialize `HwWalletContext::hw_wallet` if we reconnect to a device